version: '3.7'

services:
  nginx-sandbox:
    image: nginx:stable-alpine
    container_name: nginx-sandbox
    volumes:
      - ./var/nginx.conf:/etc/nginx/nginx.conf
      - ./var/conf.d:/etc/nginx/conf.d
      - ./var/nginxconfig.io:/etc/nginx/nginxconfig.io
      - ./var/certs/server/server.key:/etc/nginx/ssl/server.key
      - ./var/certs/server/server.crt:/etc/nginx/ssl/server.crt
      - ./var/certs/server/trust-client.crt:/etc/nginx/ssl/trust-client.crt
      - ./html/:/usr/share/nginx/html
    restart: always
    ports:
      - 443:8443